name: Build LeechCore Windows DLL

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: 

jobs:
  build-dll:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild leechcore/leechcore.vcxproj /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: leechcore-dll-x64
        path: '**/x64/Release/leechcore.dll'
