name: Build LeechCore Windows DLL

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: 

jobs:
  build-dll:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild LeechCore.sln /t:leechcore /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: leechcore-sdk
        path: |
          **/leechcore.dll
          **/leechcore.lib
          **/leechcore.h
